<?xml version="1.0" encoding="utf-8" ?>
<!-- Copyright (C) 2012 The Android Open Source Project

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.
-->

<!--
<!DOCTYPE MediaCodecs [
<!ELEMENT MediaCodecs (Decoders,Encoders)>
<!ELEMENT Decoders (MediaCodec*)>
<!ELEMENT Encoders (MediaCodec*)>
<!ELEMENT MediaCodec (Type*,Quirk*)>
<!ATTLIST MediaCodec name CDATA #REQUIRED>
<!ATTLIST MediaCodec type CDATA>
<!ELEMENT Type EMPTY>
<!ATTLIST Type name CDATA #REQUIRED>
<!ELEMENT Quirk EMPTY>
<!ATTLIST Quirk name CDATA #REQUIRED>
]>

There's a simple and a complex syntax to declare the availability of a
media codec:

A codec that properly follows the OpenMax spec and therefore doesn't have any
quirks and that only supports a single content type can be declared like so:

    <MediaCodec name="OMX.foo.bar" type="something/interesting" />

If a codec has quirks OR supports multiple content types, the following syntax
can be used:

    <MediaCodec name="OMX.foo.bar" >
        <Type name="something/interesting" />
        <Type name="something/else" />
        ...
        <Quirk name="requires-allocate-on-input-ports" />
        <Quirk name="requires-allocate-on-output-ports" />
        <Quirk name="output-buffers-are-unreadable" />
    </MediaCodec>

Only the three quirks included above are recognized at this point:

"requires-allocate-on-input-ports"
    must be advertised if the component does not properly support specification
    of input buffers using the OMX_UseBuffer(...) API but instead requires
    OMX_AllocateBuffer to be used.

"requires-allocate-on-output-ports"
    must be advertised if the component does not properly support specification
    of output buffers using the OMX_UseBuffer(...) API but instead requires
    OMX_AllocateBuffer to be used.

"output-buffers-are-unreadable"
    must be advertised if the emitted output buffers of a decoder component
    are not readable, i.e. use a custom format even though abusing one of
    the official OMX colorspace constants.
    Clients of such decoders will not be able to access the decoded data,
    naturally making the component much less useful. The only use for
    a component with this quirk is to render the output to the screen.
    Audio decoders MUST NOT advertise this quirk.
    Video decoders that advertise this quirk must be accompanied by a
    corresponding color space converter for thumbnail extraction,
    matching surfaceflinger support that can render the custom format to
    a texture and possibly other code, so just DON'T USE THIS QUIRK.

    2012/07/13 config for MTK OMX Media Codecs, created by Morris Yang (mtk03147)
-->

<MediaCodecs>
    <Encoders>
        <!-- MTK codec -->
        <MediaCodec name="OMX.MTK.VIDEO.ENCODER.MPEG4" type="video/mp4v-es" update="true">
            <Limit name="measured-frame-rate-176x144" range="235-818" />
            <Limit name="measured-frame-rate-352x288" range="145-506" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.ENCODER.H263" type="video/3gpp" update="true">
            <Limit name="measured-frame-rate-176x144" range="238-828" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.ENCODER.AVC" type="video/avc" update="true">
            <Limit name="measured-frame-rate-320x240" range="161-561" />
            <Limit name="measured-frame-rate-720x480" range="67-234" />
            <Limit name="measured-frame-rate-1280x720" range="62-141" />
            <Limit name="measured-frame-rate-1920x1080" range="55-122" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.ENCODER.HEVC" type="video/hevc" update="true">
            <Limit name="measured-frame-rate-320x240" range="161-561" />
            <Limit name="measured-frame-rate-640x480" range="67-234" />
            <Limit name="measured-frame-rate-1280x720" range="45-100" />
            <Limit name="measured-frame-rate-3840x2160" range="11-24" />
        </MediaCodec>
        <!-- Google codec -->
        <MediaCodec name="OMX.google.mpeg4.encoder" type="video/mp4v-es" update="true">
            <Limit name="measured-frame-rate-176x144" range="369-812" />
        </MediaCodec>
        <MediaCodec name="OMX.google.h263.encoder" type="video/3gpp" update="true">
            <Limit name="measured-frame-rate-176x144" range="347-764" />
        </MediaCodec>
        <MediaCodec name="OMX.google.h264.encoder" type="video/avc" update="true">
            <Limit name="measured-frame-rate-320x240" range="207-455" />
            <Limit name="measured-frame-rate-720x480" range="92-203" />
        </MediaCodec>
        <MediaCodec name="OMX.google.vp8.encoder" type="video/x-vnd.on2.vp8" update="true">
            <Limit name="measured-frame-rate-320x180" range="65-179" />
            <Limit name="measured-frame-rate-640x360" range="45-156" />
        </MediaCodec>
    </Encoders>
    <Decoders>
        <!-- MTK codec -->
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.MPEG4" type="video/mp4v-es" update="true">
            <Limit name="measured-frame-rate-176x144" range="350-550" />
            <Limit name="measured-frame-rate-480x360" range="136-474" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.H263" type="video/3gpp" update="true">
            <Limit name="measured-frame-rate-176x144" range="274-602" />
            <Limit name="measured-frame-rate-352x288" range="233-513" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.AVC" type="video/avc" update="true">
            <Limit name="measured-frame-rate-320x240" range="186-646" />
            <Limit name="measured-frame-rate-720x480" range="124-433" />
            <Limit name="measured-frame-rate-1280x720" range="74-256" />
            <Limit name="measured-frame-rate-1920x1080" range="55-122" />
        </MediaCodec>
         <MediaCodec name="OMX.MTK.VIDEO.DECODER.HEVC" type="video/hevc" update="true">
            <Limit name="measured-frame-rate-352x288" range="177-615" />
            <Limit name="measured-frame-rate-720x480" range="142-494" />
            <Limit name="measured-frame-rate-1280x720" range="75-262" />
            <Limit name="measured-frame-rate-1920x1080" range="38-132" />
            <Limit name="measured-frame-rate-3840x2160" range="26-58" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.VPX" type="video/x-vnd.on2.vp8" update="true">
            <Limit name="measured-frame-rate-320x180" range="158-549" />
            <Limit name="measured-frame-rate-640x360" range="91-315" />
            <Limit name="measured-frame-rate-1280x720" range="65-142" />
            <Limit name="measured-frame-rate-1920x1080" range="23-79" />
        </MediaCodec>
	<!-- prize modify YZHD, measured-frame-rate-3840x2160  range 7-25  to 24-50 for cts
	CtsMediaTestCases android.media.cts.VideoDecoderPerfTest#testVp9Other0Perf3840x2160 ,20190806 -->
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.VP9" type="video/x-vnd.on2.vp9" update="true">
            <Limit name="measured-frame-rate-320x180" range="237-522" />
            <Limit name="measured-frame-rate-640x360" range="170-373" />
            <Limit name="measured-frame-rate-1280x720" range="89-196" />
            <Limit name="measured-frame-rate-1920x1080" range="55-121" />
            <Limit name="measured-frame-rate-3840x2160" range="24-50" />
        </MediaCodec>
        <!-- Google codec -->
        <MediaCodec name="OMX.google.mpeg4.decoder" type="video/mp4v-es" update="true">
            <Limit name="measured-frame-rate-176x144" range="471-1036" />
            <Limit name="measured-frame-rate-480x360" range="100-250" />
        </MediaCodec>
        <MediaCodec name="OMX.google.h263.decoder" type="video/3gpp" update="true">
            <Limit name="measured-frame-rate-176x144" range="450-990" />
            <Limit name="measured-frame-rate-352x288" range="128-297" />
        </MediaCodec>
        <MediaCodec name="OMX.google.h264.decoder" type="video/avc" update="true">
            <Limit name="measured-frame-rate-320x240" range="351-773" />
            <Limit name="measured-frame-rate-720x480" range="84-184" />
            <Limit name="measured-frame-rate-1280x720" range="28-96" />
        </MediaCodec>
         <MediaCodec name="OMX.google.hevc.decoder" type="video/hevc" update="true">
            <Limit name="measured-frame-rate-352x288" range="182-634" />
            <Limit name="measured-frame-rate-720x480" range="81-282" />
            <Limit name="measured-frame-rate-1280x720" range="47-104" />
        </MediaCodec>
        <MediaCodec name="OMX.google.vp8.decoder" type="video/x-vnd.on2.vp8" update="true">
            <Limit name="measured-frame-rate-320x180" range="288-1003" />
            <Limit name="measured-frame-rate-640x360" range="103-359" />
            <Limit name="measured-frame-rate-1280x720" range="20-68" />
            <Limit name="measured-frame-rate-1920x1080" range="14-50" />
        </MediaCodec>
        <MediaCodec name="OMX.google.vp9.decoder" type="video/x-vnd.on2.vp9" update="true">
            <Limit name="measured-frame-rate-320x180" range="833-1832" />
            <Limit name="measured-frame-rate-640x360" range="109-378" />
            <Limit name="measured-frame-rate-1280x720" range="57-126" />
        </MediaCodec>
    </Decoders>
</MediaCodecs>
